version: '2'
services:
  catinygateway-app:
    extends:
      file: catiny-gateway.yml
      service: catinygateway-app
  catinygateway-mariadb:
    extends:
      file: mariadb.yml
      service: catinygateway-mariadb
  catinygateway-redis:
    extends:
      file: redis.yml
      service: catinygateway-redis
  catinygateway-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinygateway-elasticsearch
#  jhipster-registry:
#    extends:
#      file: jhipster-registry.yml
#      service: jhipster-registry
#    environment:
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
#      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
