version: '2'
services:
  catinygateway-app:
    extends:
      file: catiny-gateway.yml
      service: catinygateway-app
  catinygateway-mariadb:
    extends:
      file: mariadb.yml
      service: catinygateway-mariadb
  catinygateway-redis:
    extends:
      file: redis.yml
      service: catinygateway-redis
  catinygateway-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: catinygateway-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
