version: '2'
services:
  catinygateway-app:
    image: catinygateway
    environment:
      - _JAVA_OPTIONS=-Xms64m -Xmx512m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mariadb://catinygateway-mariadb:3306/catinygateway?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JHIPSTER_CACHE_REDIS_SERVER=redis://catinygateway-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
      - SPRING_DATA_JEST_URI=http://catinygateway-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://catinygateway-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - 10000:10000
