version: '2'
services:
  catinygateway-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    ports:
      - 14000:9200
      - 14001:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms64m -Xmx512m'
      - 'discovery.type=single-node'
