version: '2'
services:
  catinygateway-mariadb:
    image: mariadb:10.5.3
    volumes:
      - /root/volumes/jhipster/CatinyGateway/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=catinygateway
    ports:
      - 11000:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
