version: '2'
services:
  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - 17000:8080
    volumes:
      - ../resource/swagger/:/tmp
    environment:
      - SWAGGER_FILE=/tmp/api.yml
